[package]
name = "jakgro"
version = "0.1.0"
edition = "2024"
rust-version = "1.85"

[dependencies]
cozy-chess = { version = "0.3.4", git = "https://github.com/JackThomson2/cozy-chess", branch = "board-state-save-restore" }
mimalloc = "0.1.48"

[[bench]]
name = "search"
harness = false

[profile.release]
lto = "fat"
codegen-units = 1
panic = "abort"
strip = "debuginfo"
